"""Create SQLite table for samples

Revision ID: 941e45ee5e96
Revises: 
Create Date: 2025-07-15 09:55:47.508132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941e45ee5e96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('sample_type', sa.Enum('blood', 'saliva', 'tissue', name='sampletype'), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('collected', 'processing', 'archived', name='statustype'), nullable=False),
    sa.Column('storage_location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sample_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    # ### end Alembic commands ###
